In [20]:
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [21]:
df = pd.read_csv("../Dataset/processed_data.csv")

print("Dataset Shape :", df.shape)

df.head()

Dataset Shape : (36457, 18)

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,TARGET
0,1.425224,1.278126,0.698338,-0.579661,2.365845,0.923758,-1.563576,-1.433026,2.855131,0.945169,-0.463532,0.0,1.853127,-0.646578,-0.313952,0.056606,-0.217680,1
1,1.425224,1.278126,0.698338,-0.579661,2.365845,0.923758,-1.563576,-1.433026,2.855131,0.945169,-0.463532,0.0,1.853127,-0.646578,-0.313952,0.056606,-0.217680,1
2,1.425224,1.278126,0.698338,-0.579661,-0.728827,0.923758,0.673104,-0.385405,-0.297250,-1.309091,-0.438774,0.0,-0.539628,-0.646578,-0.313952,2.274732,-0.217680,1
3,-0.701644,-0.782396,0.698338,-0.579661,0.818509,-1.383035,0.673104,1.709838,-0.297250,-0.746300,-0.452700,0.0,-0.539628,1.546603,3.185203,1.720201,-1.314564,1
4,-0.701644,-0.782396,0.698338,-0.579661,0.818509,-1.383035,0.673104,1.709838,-0.297250,-0.746300,-0.452700,0.0,-0.539628,1.546603,3.185203,1.720201,-1.314564,1

In [22]:
X = df.drop("TARGET", axis=1)

y = df["TARGET"]

feature_names = X.columns.tolist()

joblib.dump(
    feature_names,
    "../Models/feature_names.pkl"
)

print("Feature Names Saved Successfully.")

Feature Names Saved Successfully.

In [23]:
X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.20,

    random_state=42,

    stratify=y

)

In [24]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

joblib.dump(
    scaler,
    "../Models/scaler.pkl"
)

print("Scaler Saved Successfully.")

Scaler Saved Successfully.

In [25]:
models = {

    "Logistic Regression":

        LogisticRegression(
            max_iter=1000
        ),

    "Decision Tree":

        DecisionTreeClassifier(

            random_state=42,

            class_weight="balanced"

        ),

    "Random Forest":

        RandomForestClassifier(

            n_estimators=300,

            random_state=42,

            class_weight="balanced"

        )

}

In [26]:
results = []

trained_models = {}

for name, model in models.items():

    model.fit(

        X_train_scaled,

        y_train

    )

    trained_models[name] = model

    prediction = model.predict(

        X_test_scaled

    )

    accuracy = accuracy_score(

        y_test,

        prediction

    )

    results.append({

        "Model": name,

        "Accuracy": accuracy * 100

    })

results = pd.DataFrame(results)

results.sort_values(

    by="Accuracy",

    ascending=False,

    inplace=True

)

results

                 Model   Accuracy
0  Logistic Regression  98.313220
2        Random Forest  96.215030
1        Decision Tree  95.858475

In [27]:
for name, model in trained_models.items():

    print("="*60)

    print(name)

    print("="*60)

    prediction = model.predict(

        X_test_scaled

    )

    print(

        "Accuracy:",

        accuracy_score(

            y_test,

            prediction

        )

    )

    print()

    print("Confusion Matrix")

    print(

        confusion_matrix(

            y_test,

            prediction

        )

    )

    print()

    print("Classification Report")

    print(

        classification_report(

            y_test,

            prediction

        )

    )

    print("\n")

============================================================
Logistic Regression
============================================================
Accuracy: 0.9831321996708722

Confusion Matrix
[[   0  123]
 [   0 7169]]

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       123
           1       0.98      1.00      0.99      7169

    accuracy                           0.98      7292
   macro avg       0.49      0.50      0.50      7292
weighted avg       0.97      0.98      0.97      7292



============================================================
Decision Tree
============================================================
Accuracy: 0.9585847504114098

Confusion Matrix
[[  58   65]
 [ 237 6932]]

Classification Report
              precision    recall  f1-score   support

           0       0.20      0.47      0.28       123
           1       0.99      0.97      0.98      7169

    accuracy                           0.96      7292
   macro avg       0.59      0.72      0.63      7292
weighted avg       0.98      0.96      0.97      7292



============================================================
Random Forest
============================================================

C:\Users\USER1\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\USER1\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\USER1\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Accuracy: 0.9621503017004936

Confusion Matrix
[[  56   67]
 [ 209 6960]]

Classification Report
              precision    recall  f1-score   support

           0       0.21      0.46      0.29       123
           1       0.99      0.97      0.98      7169

    accuracy                           0.96      7292
   macro avg       0.60      0.71      0.63      7292
weighted avg       0.98      0.96      0.97      7292

In [28]:
best_model = trained_models["Decision Tree"]

print("Final Model Selected : Decision Tree")

Final Model Selected : Decision Tree

In [29]:
joblib.dump(

    best_model,

    "../Models/card_model.joblib"

)

joblib.dump(

    scaler,

    "../Models/scaler.pkl"

)

joblib.dump(

    feature_names,

    "../Models/feature_names.pkl"

)

print("="*50)

print("Decision Tree Saved Successfully")

print("="*50)

==================================================
Decision Tree Saved Successfully
==================================================

In [30]:
print(type(best_model))

<class 'sklearn.tree._classes.DecisionTreeClassifier'>

In [32]:
import joblib

model = joblib.load("../Models/card_model.joblib")

print(type(model))

<class 'sklearn.tree._classes.DecisionTreeClassifier'>